# Generated by Django 5.0.7 on 2024-07-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('developer', 'Developer'), ('viewer', 'Viewer')], default='viewer', max_length=10),
        ),
    ]
